version: '2'
services:
  web:
    build: ./main-server
    networks:
      - back
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=test
    networks:
      - back

networks:
  back:
    driver: bridge